### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by Desvelao** [ottah/ArtifactDB#27]
Suggestions:

__DB Restructure__
- Create a **file by card** and other file for set info. It's more organized of this way in my opinion. You can check if a card is included at database, seeing file names, for example.
- Create a card and set json templates files with all fields.
- Create a script (npm run build) to build a compiled db file (cards-manifest.json) with all cards + set info. Now there are +5k lanes and it's complicated manage it.
- Maybe organize jsons card inner sets folders with set name as folder name, idk.

__Fixs__

- Rename **fileName** field to **FileName** or **Filename** due to rest fields start with capital letter.

__Images__
I found this [post](https://www.reddit.com/r/Artifact/comments/9soqiq/all_currently_revealed_cards_recreated_with/) on reddit with cards images reacreted by [u/Nocturne25](https://www.reddit.com/user/Nocturne25): [Imgur Album](https://imgur.com/a/d74gnrD). Interesting if we can't get other images, at least.

__Questions__

- Why IsSignatureCard is a boolean, maybe it could be a field with hero id instead or other field maybe?

Thank you so much for your work!

**Comment by 0ttah** [comment]
**DB Restructure**
- I've been working on an online card/db editor that hopefully I will be up online later today which makes editing and adding new cards really easy. When its up we can see if splitting up the cards into individual files would be better than the editor.

- Card and set schemas will be added to use for templates and types.

- I definitely agree about splitting up the sets into separate files as when the next set comes out the manifest will become too big to maintain. 

- I'm most likely going to be renaming all the properties to be lower case as it makes more sense especially as it is a JS library. But I'll update fileName to FileName for now.

- IsSignatureCard is boolean because the relatedIds will point to the hero card. But now that I think of it, there could be at some point a signature spell card that spawns a token card which means there will be 2 relatedIds instead of one. I'll change this to be the id of the hero.

Most of these changes will be in 3.0 so it isn't breaking peoples current stuff. I think a lot of work needs to go into the JS module and providing functions that the user can easily use for example a **getCard(id)** function.
